export enum ANIMATIONS {
    STATIC = "STATIC",
    SCROLL = "SCROLL",
    SCROLL_REVERSE = "SCROLL_REVERSE",
    CIRCLE = "CIRCLE",
    CIRCLE_REVERSE = "CIRCLE_REVERSE",
    PULSE = "PULSE"
}

export const ANIMATION_NAMES = Object.keys(ANIMATIONS)